CREATE TABLE system_status (
    id SERIAL PRIMARY KEY,
    running INT,
    sleeping INT,
    stopped INT,
    total_tasks INT,
    zombie INT,
    cpu_hi FLOAT,
    cpu_id FLOAT,
    cpu_ni FLOAT,
    cpu_si FLOAT,
    cpu_st FLOAT,
    cpu_sy FLOAT,
    cpu_us FLOAT,
    cpu_wa FLOAT,
    load_avg_1m FLOAT,
    load_avg_5m FLOAT,
    load_avg_15m FLOAT,
    mem_buff_cache FLOAT,
    mem_free FLOAT,
    mem_total FLOAT,
    mem_used FLOAT,
    swap_avail_mem FLOAT,
    swap_free FLOAT,
    swap_total FLOAT,
    swap_used FLOAT,
    system_time TIMESTAMP,
    uptime TEXT,
    users INT
);